### ISSUE TITLE
NameError: name 'node' is not defined

### ISSUE THREAD

**Issue by ngblume** [dankamongmen/canscan#11]
Hey,

there is probably something I'm missing here, but when running
"sudo python3 -m canscan socketcan can0" (can0 as SocketCAN works, since I'm getting packets in WireShark..)
is says: 
" File "/home/ngblume/.local/lib/python3.6/site-packages/canscan/__main__.py", line 52, in <module>
    CanNode = node.Node(dev=args.device, bustype=args.bustype, channel=args.channel)
NameError: name 'node' is not defined"

My understanding is, that this is caused by the object not being defined... 
But @dankamongmen: any ideas, what's causing this ??

Thanks !

Cheers
Niels

**Comment by dankamongmen** [comment]
Hey there, @ngblume ! This is my first Python project ever (after a long career of C and assembly), so whatever you see that looks dumb or broken almost certainly is.

I'll take a look at this tomorrow early, but know that CANScan is not a very advanced tool at all. I'd be happy to have another contributor join up, though!

**Comment by ngblume** [comment]
Thanks for your answer...
I was just looking for a simple tool that utilized python-can to get an idea of how to use it...

**Comment by ngblume** [comment]
Forget to close this one...
